/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  ULWOS testing                          */
/*      FILE         :  main.c                                 */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RL78 - G13                             */
/*      CPU TYPE     :  R5F100LE                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                   
                                                                                            
                                                                                            
/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 02/26/2016                                        */
/************************************************************************/

#include "iodefine.h"
#include "iodefine_ext.h"
#include "myrl78.h"
#include "interrupt_handlers.h"
#include "ulwos.h"

#define LED P7_bit.no7
#define LED2 P7_bit.no6

void __attribute__ ((noreturn)) task1(void){
	volatile long int count;
	while (1){
		LED = 0;
		for (count=0; count<100000;count++);
		LED = 1;
		for (count=0; count<100000;count++);
	}
}

void __attribute__ ((noreturn)) task2(void){
	volatile long int count;
	while (1){
		LED2 = 0;
		for (count=0; count<200000;count++);
		LED2 = 1;
		for (count=0; count<200000;count++);
	}
}

int main(void){
    PM7_bit.no7 = 0;
    PM7_bit.no6 = 0;
    LED = 0;
	ULWOS_TASKHANDLER tk1 = ulwos_create_task(&task1);
	ULWOS_TASKHANDLER tk2 = ulwos_create_task(&task2);
	ulwos_start();
	// the following code is never reached!!! It is here "just in case" ;)
	while (1){
	}
}
