/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  ULWOS testing                          */
/*      FILE         :  main.c                                 */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RL78 - G13                             */
/*      CPU TYPE     :  R5F100LE                               */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                   
                                                                                            
                                                                                            
/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 02/26/2016                                        */
/************************************************************************/

#include "iodefine.h"
#include "iodefine_ext.h"
#include "myrl78.h"
#include "interrupt_handlers.h"
#include "ulwos.h"
#include "lcd_8x2.h"

#define LED 	P6_bit.no3
#define LED_DIR PM6_bit.no3

volatile unsigned long counter;

void task1(void){
	volatile unsigned long count;
	LED_DIR = 0;
	while (1){
		LED = 0;
		for (count=0; count<100000;count++) counter=count;
		LED = 1;
		for (count=0; count<100000;count++) counter=count;
	}
}

void task2(void){
	volatile unsigned char aux;
	volatile unsigned long temp;
	LCD_init(DISPLAY_8x5|_2LINES,DISPLAY_ON|CURSOR_OFF|CURSOR_FIXED);
	while (1){
		LCD_write_char('\f');   // apaga o display
		LCD_pos_xy(0,0);
		LCD_write_string("Testing");
		for (aux=0;aux<100;aux++){
			LCD_pos_xy(0,1);
			LCD_print_char(aux);
			for (temp=0;temp<500000;temp++);
		}
	}
}

void main(void){
	ULWOS_TASKHANDLER tk1 = ulwos_create_task(&task1);
	ULWOS_TASKHANDLER tk2 = ulwos_create_task(&task2);
	ulwos_start();
	// the following code is never executed!!! It is here "just in case" ;)
	while (1){
	}
}
